decoder_params:
  bidirectional: false
  dropout: 0
  hidden_size: 512
  num_layers: 1
device: !!python/object/apply:torch.device
- cuda
embedding_dim: 256
encoder_out_dim_list:
- 256
encoder_params:
  bidirectional: false
  dropout: 0
  hidden_size: 512
  num_layers: 1
latent_dim: 64
learning_rate: 0.001
max_len: 109
vocab: !!python/object:src.token.SmilesVocabulary
  char_list:
  - ' '
  - '!'
  - '?'
  - '[Br]'
  - '[Branch1]'
  - '[C]'
  - '[#Branch2]'
  - '[=Branch1]'
  - '[=Branch2]'
  - '[=C]'
  - '[=O]'
  - '[Branch2]'
  - '[N]'
  - '[O]'
  - '[Ring1]'
  - '[#C]'
  - '[=N]'
  - '[=S]'
  - '[Ring2]'
  - '[#Branch1]'
  - '[S]'
  - '[Cl]'
  - '[#N]'
  - '[=Ring1]'
  - '[F]'
  - '[NH1]'
  - '[P]'
  - '[=Ring2]'
  - '[N+1]'
  - '[O-1]'
  - '[I]'
  - '[=N+1]'
  - '[=N-1]'
  - '[S+1]'
  - '[B]'
  - '[=P]'
  - '[Si]'
  - '[Cl+1]'
  - '[H]'
  - '[#N+1]'
  - '[C-1]'
  - '[N-1]'
  - '[PH1]'
  - '[P+1]'
  - '[B-1]'
  - '[Se]'
  - '[NH1+1]'
  - '[=O+1]'
  - '[OH0]'
  - '[=S+1]'
  - '[=Se]'
  - '[S-1]'
  - '[I+1]'
  - '[NH3+1]'
  - '[O+1]'
  - '[NH2+1]'
  - '[BH3-1]'
  - '[BH2-1]'
  - '[C+1]'
  - '[=NH2+1]'
  - '[=C-1]'
  - '[F+1]'
  - '[SiH1]'
  - '[CH1-1]'
  - '[=NH1+1]'
  - '[SH1]'
  - '[=Se+1]'
  - '[=PH1]'
  - '[#C-1]'
  - '[SiH2]'
  - '[NH1-1]'
  - '[CH1+1]'
  - '[I+2]'
  - '[F-1]'
  - '[Si-1]'
  - '[=OH1+1]'
  - '[SiH1-1]'
  - '[BH1-1]'
  - '[#O+1]'
  - '[CH2+1]'
  - '[NH0]'
  - '[=SH1]'
  - '[SeH1]'
  - '[Cl-1]'
  - '[CH1]'
  - '[=B]'
  - '[Se-1]'
  - '[SeH2]'
  - '[Se+1]'
  - '[BH0]'
  - '[CH2]'
  - '[Cl+3]'
  - '[I+3]'
  - '[Br-1]'
  - '[=Si]'
  - '[Cl+2]'
  - '[PH2+1]'
  - '[Br+2]'
  - '[=B-1]'
  - '[#S]'
  - '[OH1+1]'
