epochs: 10
batch_size: 128
learning_rate: 1e-3
latent_dim: 64
embedding_dim: 256
encoder_params:
  hidden_size: 512
  num_layers: 1
  dropout: 0
  bidirectional: False
decoder_params:
  hidden_size: 512
  num_layers: 1
  dropout: 0
  bidirectional: False
encoder_out_dim_list: [256]
output_dir: ./reports/
n_log_step: 50
seed: 42
