bayopt_bounds:
  batch_size:
  - 3
  - 10
  dense_units:
  - 3
  - 10
  embedding_dim:
  - 3
  - 10
  learning_rate:
  - 1e-4
  - 1e-2
  lstm_units:
  - 3
  - 10
dataset:
  filepath: data/processed/FreeSolv_SAMPL.csv
  prop: expt
hyper_parameters:
  model:
    dense_units: 32
    embedding_dim: 16
    lstm_units: 512
    vocab_size: 35
  other:
    batch_size: 8
    learning_rate: 0.0015197980620034217
token:
  max_length: 51
  vocabulary:
  - pad
  - unk
  - '#'
  - '[C@]'
  - O
  - '[O-]'
  - '[C@H]'
  - Br
  - \
  - '2'
  - S
  - ' '
  - '[C@@H]'
  - '[C@@]'
  - F
  - n
  - '[N+]'
  - s
  - '4'
  - )
  - c
  - '='
  - /
  - C
  - '[S+2]'
  - '-'
  - '5'
  - I
  - Cl
  - '1'
  - N
  - P
  - (
  - '3'
  - '[nH]'
train:
  augmentation: true
  bayopt_n_epochs: 30
  bayopt_n_trials: 50
  bayopt_on: true
  loss_func: MSE
  n_epochs: 100
  scaling: true
  seed: 42
  tf16: false
