vocab:
- ' '
- '!'
- '?'
- (
- )
- '1'
- '2'
- '='
- C
- F
- 'N'
- O
- c
- l
- 'n'
- '3'
- '4'
- '5'
- '-'
- S
- H
- '['
- ']'
- o
- B
- r
- '6'
- '7'
- '#'
- s
- +
- i
- I
- P
- e
- '8'
- '9'
- '%'
- '0'
- p
- b
hidden_size: 512
n_layers: 3
learning_rate: 0.001
