decoder_params:
  bidirectional: false
  dropout: 0
  hidden_size: 512
  num_layers: 1
embedding_dim: 256
encoder_out_dim_list:
- 256
encoder_params:
  bidirectional: false
  dropout: 0
  hidden_size: 512
  num_layers: 1
latent_dim: 64
max_len: 102
vocab:
- ' '
- '!'
- '?'
- (
- )
- B
- C
- r
- '-'
- '1'
- '2'
- '='
- N
- O
- c
- '3'
- S
- '4'
- l
- n
- '#'
- o
- F
- H
- '['
- ']'
- '5'
- P
- s
- +
- I
- '6'
- i
- '7'
- e
- '8'
