decoder_params:
  bidirectional: false
  dropout: 0
  hidden_size: 512
  num_layers: 1
embedding_dim: 256
encoder_out_dim_list:
- 256
encoder_params:
  bidirectional: false
  dropout: 0
  hidden_size: 512
  num_layers: 1
latent_dim: 64
max_len: 102
vocab:
- ' '
- '!'
- '?'
- (
- )
- '1'
- '2'
- '='
- C
- F
- N
- O
- c
- l
- n
- '3'
- '4'
- '5'
- '-'
- S
- H
- '['
- ']'
- o
- B
- r
- '6'
- '7'
- '#'
- s
- +
- i
- I
- P
- e
- '8'
- '9'
- '%'
- '0'
- p
- b
