bayopt_bounds:
  dense_units:
  - 3
  - 10
  embedding_dim:
  - 3
  - 10
  learning_rate:
  - 1e-4
  - 1e-2
  lstm_units:
  - 3
  - 10
dataset:
  dataset_path: ../datasets/processed/FreeSolv_SAMPL.csv
  output_path: ../reports/FreeSolv
  prop_col_name: expt
  smiles_col_name: smiles
hyper_parameters:
  model:
    dense_units: 256
    embedding_dim: 512
    lstm_units: 32
    vocab_size: 35
  other:
    learning_rate: 0.0012894414393074191
ref_hyperparam:
  dense_units: 512,
  embedding_dim: 512,
  learning_rate: 1e-3
  lstm_units: 512,
token:
  max_length: 51
  vocabulary:
  - pad
  - unk
  - S
  - c
  - '-'
  - '[C@]'
  - n
  - '[O-]'
  - F
  - '5'
  - '[S+2]'
  - '[C@@H]'
  - s
  - '[nH]'
  - '='
  - P
  - /
  - '1'
  - '[N+]'
  - \
  - '4'
  - I
  - '[C@@]'
  - '3'
  - O
  - C
  - N
  - '#'
  - (
  - Cl
  - '[C@H]'
  - )
  - ' '
  - '2'
  - Br
train:
  augmentation: true
  batch_size: 128
  bayopt_n_epochs: 10
  bayopt_n_trials: 50
  bayopt_on: true
  loss_func: MSE
  n_early_stopping: 30
  n_epochs: 100
  scaling: true
  seed: 42
  tf16: true
