bayopt_bounds:
  lstm_units: [3, 10]
  dense_units: [3, 10]
  embedding_dim: [3, 10]
  batch_size: [3, 7]
  learning_rate: [1e-5, 1e-1]

train:
  augmentation: true
  bayopt_on: true
  bayopt_n_epochs: 10
  bayopt_n_trials: 50
  n_epochs: 100
  tf16: false
  loss_func: MSE
  scaling: true
  seed: 1

dataset:
  filepath: data/processed/Density.csv
  smiles: smiles
  prop: density
